language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
  - pip3 install pytest pytest-cov
  - pip3 install coverage
# command to run tests
script:
  - py.test -vv --cov

after_success:
  - coveralls
